const usersData = [
  {
    key: "1",
    fullname: "Galen Slixby",
    email: "gslixby0@email.com",
    role: "Editor",
    plan: "Enterprise",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    gender: "male",
  },
  {
    key: "2",
    fullname: "Halsey Redmore",
    email: "hredmore1@email.com",
    role: "Author",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    gender: "male",
  },
  {
    key: "3",
    fullname: "Marjory Sicely",
    email: "msicely2@email.com",
    role: "Maintainer",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
    gender: "female",
  },
  {
    key: "4",
    fullname: "Cyrill Risby",
    email: "crisby3@email.com",
    role: "Maintainer",
    plan: "Team",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
    gender: "male",
  },
  {
    key: "5",
    fullname: "Maggy Hurran",
    email: "mhurran4@email.com",
    role: "Subscriber",
    plan: "Enterprise",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
    gender: "female",
  },
  {
    key: "6",
    fullname: "Silvan Halstead",
    email: "shalstead5@email.com",
    role: "Author",
    plan: "Company",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
    gender: "male",
  },
  {
    key: "7",
    fullname: "Breena Gallemore",
    email: "bgallemore6@email.com",
    role: "Subscriber",
    plan: "Company",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
    gender: "female",
  },
  {
    key: "8",
    fullname: "Kathryne Liger",
    email: "kliger7@email.com",
    role: "Author",
    plan: "Enterprise",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    gender: "female",
  },
  {
    key: "9",
    fullname: "Franz Scotfurth",
    email: "fscotfurth8@email.com",
    role: "Subscriber",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    gender: "male",
  },
  {
    key: "10",
    fullname: "Jillene Bellany",
    email: "jbellany9@email.com",
    role: "Maintainer",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    gender: "female",
  },
  {
    key: "11",
    fullname: "User Eleven",
    email: "user11@email.com",
    role: "Subscriber",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    gender: "male",
  },
  {
    key: "12",
    fullname: "User Twelve",
    email: "user12@email.com",
    role: "Editor",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    gender: "female",
  },
  {
    key: "13",
    fullname: "User Thirteen",
    email: "user13@email.com",
    role: "Author",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    gender: "male",
  },
  {
    key: "14",
    fullname: "User Fourteen",
    email: "user14@email.com",
    role: "Maintainer",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    gender: "female",
  },
  {
    key: "15",
    fullname: "User Fifteen",
    email: "user15@email.com",
    role: "Subscriber",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    gender: "male",
  },
  {
    key: "16",
    fullname: "User Sixteen",
    email: "user16@email.com",
    role: "Editor",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    gender: "female",
  },
  {
    key: "17",
    fullname: "User Seventeen",
    email: "user17@email.com",
    role: "Author",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    gender: "male",
  },
  {
    key: "18",
    fullname: "User Eighteen",
    email: "user18@email.com",
    role: "Maintainer",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    gender: "female",
  },
  {
    key: "19",
    fullname: "User Nineteen",
    email: "user19@email.com",
    role: "Subscriber",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    gender: "male",
  },
  {
    key: "20",
    fullname: "User Twenty",
    email: "user20@email.com",
    role: "Editor",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
    gender: "female",
  },
];

export default usersData;
