const usersData = [
  {
    key: "1",
    user: "Galen Slixby",
    email: "gslixby0@email.com",
    role: "Editor",
    plan: "Enterprise",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    key: "2",
    user: "Halsey Redmore",
    email: "hredmore1@email.com",
    role: "Author",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    key: "3",
    user: "Marjory Sicely",
    email: "msicely2@email.com",
    role: "Maintainer",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    key: "4",
    user: "Cyrill Risby",
    email: "crisby3@email.com",
    role: "Maintainer",
    plan: "Team",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    key: "5",
    user: "Maggy Hurran",
    email: "mhurran4@email.com",
    role: "Subscriber",
    plan: "Enterprise",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    key: "6",
    user: "Silvan Halstead",
    email: "shalstead5@email.com",
    role: "Author",
    plan: "Company",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    key: "7",
    user: "Breena Gallemore",
    email: "bgallemore6@email.com",
    role: "Subscriber",
    plan: "Company",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    key: "8",
    user: "Kathryne Liger",
    email: "kliger7@email.com",
    role: "Author",
    plan: "Enterprise",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    key: "9",
    user: "Franz Scotfurth",
    email: "fscotfurth8@email.com",
    role: "Subscriber",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    key: "10",
    user: "Jillene Bellany",
    email: "jbellany9@email.com",
    role: "Maintainer",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  // Add 10 more users here
  {
    key: "11",
    user: "User Eleven",
    email: "user11@email.com",
    role: "Subscriber",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    key: "12",
    user: "User Twelve",
    email: "user12@email.com",
    role: "Editor",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    key: "13",
    user: "User Thirteen",
    email: "user13@email.com",
    role: "Author",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  {
    key: "14",
    user: "User Fourteen",
    email: "user14@email.com",
    role: "Maintainer",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
  },
  {
    key: "15",
    user: "User Fifteen",
    email: "user15@email.com",
    role: "Subscriber",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
  },
  {
    key: "16",
    user: "User Sixteen",
    email: "user16@email.com",
    role: "Editor",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
  },
  {
    key: "17",
    user: "User Seventeen",
    email: "user17@email.com",
    role: "Author",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
  },
  {
    key: "18",
    user: "User Eighteen",
    email: "user18@email.com",
    role: "Maintainer",
    plan: "Team",
    status: "Pending",
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
  },
  {
    key: "19",
    user: "User Nineteen",
    email: "user19@email.com",
    role: "Subscriber",
    plan: "Company",
    status: "Inactive",
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
  },
  {
    key: "20",
    user: "User Twenty",
    email: "user20@email.com",
    role: "Editor",
    plan: "Enterprise",
    status: "Active",
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
  },
];

export default usersData;
